### ISSUE TITLE
Motion-Frank: Not an IB issue but...

### ISSUE THREAD

**Issue by Bodacious** [rubymotion-community/ib#89]
Hi guys,

[I'm having problems getting Frank to work well with IB](https://github.com/cyrusinnovation/motion-frank/issues/7). I know this isn't strictly an issue with IB, but I wondered if you could offer some guidance all the same, since the Frank guys seem to have given up on the project.

The issue appears to be that Frank expects an `.xcodeproj` file in my app directory. Since IB creates one, Frank is defaulting to using that. This leads to a bunch of load errors.  

Can you suggest any approaches I can try?

**Comment by MarkVillacampa** [comment]
Answered here: https://github.com/cyrusinnovation/motion-frank/issues/7#issuecomment-239858058

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781539/94b8b6f2-b7be-11e6-9e39-9b88b3f96e40.png)
